[package]
name = "disc"
version = "0.1.0"
edition = "2021"
authors = ["Edvin Flodin <edvin.flodin+discrs@gmail.com>"]
documentation = "https://docs.rs/disc/0.1.0/disc/"
license = "MIT or Apache-2.0"

[dependencies]
disc-derive = { path = "../disc-derive", version = "0.1.0" }